spring:
  data:
    mongodb:
      host: mongodb
      #host: localhost
      #host: host.docker.internal
      username: root
      password: pwd1234
      port: 27017
      database: shop
      authentication-database: admin
  thymeleaf:
    reactive:
      max-chunk-size: 1024